In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("."))


# Any results you write to the current directory are saved as output.

['.ipynb_checkpoints', 'atis-dataset-from-ms-cntk.ipynb', 'atis.dict.intent.csv', 'atis.dict.slots.csv', 'atis.dict.vocab.csv', 'atis.test.intent.csv', 'atis.test.pkl', 'atis.test.query.csv', 'atis.test.slots.csv', 'atis.train.intent.csv', 'atis.train.pkl', 'atis.train.query.csv', 'atis.train.slots.csv', 'atis.zip']


In [2]:
import pickle

DATA_DIR="."

def load_ds(fname='atis.train.pkl'):
    with open(fname, 'rb') as stream:
        ds,dicts = pickle.load(stream)
    print('Done  loading: ', fname)
    print('      samples: {:4d}'.format(len(ds['query'])))
    print('   vocab_size: {:4d}'.format(len(dicts['token_ids'])))
    print('   slot count: {:4d}'.format(len(dicts['slot_ids'])))
    print(' intent count: {:4d}'.format(len(dicts['intent_ids'])))
    return ds,dicts

# Load ATIS Dataset

In [ ]:
train_ds, dicts = load_ds(os.path.join(DATA_DIR,'atis.train.pkl'))
test_ds, dicts  = load_ds(os.path.join(DATA_DIR,'atis.test.pkl'))

In [15]:
query[1]

array([178, 916, 429, 228, 244, 444, 682, 851, 247, 654, 845, 606, 179],
      dtype=int64)

In [16]:
' '.join(map(i2t.get, query[i]))

'BOS round trip fares from pittsburgh to philadelphia under 1000 dollars EOS'

In [17]:
i2t[query[i][j]]

'EOS'

# Show first few samples

In [20]:
t2i, s2i, in2i = map(dicts.get, ['token_ids', 'slot_ids','intent_ids'])
i2t, i2s, i2in = map(lambda d: {d[k]:k for k in d.keys()}, [t2i,s2i,in2i])
query, slots, intent =  map(train_ds.get, ['query', 'slot_labels', 'intent_labels'])

for i in range(5):
    print('{:4d}:{:>15}: {}'.format(i, i2in[intent[i][0]],
                                    ' '.join(map(i2t.get, query[i]))))
    for j in range(len(query[i])):
        print('{:>33} {:>40}'.format(i2t[query[i][j]],
                                     i2s[slots[i][j]]  ))
    print('*'*74)

   0:         flight: BOS i want to fly from boston at 838 am and arrive in denver at 1110 in the morning EOS
                              BOS                                        O
                                i                                        O
                             want                                        O
                               to                                        O
                              fly                                        O
                             from                                        O
                           boston                      B-fromloc.city_name
                               at                                        O
                              838                       B-depart_time.time
                               am                       I-depart_time.time
                              and                                        O
                           arrive                                

In [28]:
t2i, s2i, in2i = map(dicts.get, ['token_ids', 'slot_ids','intent_ids'])
i2t, i2s, i2in = map(lambda d: {d[k]:k for k in d.keys()}, [t2i,s2i,in2i])
query, slots, intent =  map(train_ds.get, ['query', 'slot_labels', 'intent_labels'])

for i in range(5):
    print(' '.join(map(i2t.get, query[i])))
    print(query[i])
    s = []
    s2 = [intent[i][0]]
    for j in range(len(query[i])):
        #print('{:>33} {:>40}'.format(i2t[query[i][j]],
        #                             i2s[slots[i][j]]  ))
        s.append(i2s[slots[i][j]])
        s2.append(slots[i][j])
    print(i2in[intent[i][0]], ' '.join(s))
    print(s2)
    print('*'*74)

BOS i want to fly from boston at 838 am and arrive in denver at 1110 in the morning EOS
[178 479 902 851 431 444 266 240 168 210 215 236 482 351 240  27 482 827
 606 179]
flight O O O O O O B-fromloc.city_name O B-depart_time.time I-depart_time.time O O O B-toloc.city_name O B-arrive_time.time O O B-arrive_time.period_of_day O
[14, 128, 128, 128, 128, 128, 128, 48, 128, 35, 100, 128, 128, 128, 78, 128, 14, 128, 128, 12, 128]
**************************************************************************
BOS what flights are available from pittsburgh to baltimore on thursday morning EOS
[178 916 429 228 244 444 682 851 247 654 845 606 179]
flight O O O O O O B-fromloc.city_name O B-toloc.city_name O B-depart_date.day_name B-depart_time.period_of_day O
[14, 128, 128, 128, 128, 128, 128, 48, 128, 78, 128, 26, 33, 128]
**************************************************************************
BOS what is the arrival time in san francisco for the 755 am flight leaving washington EOS
[178 916 498

In [25]:
intent[i]

array([3], dtype=int64)

In [23]:
slots[i][j]

128

In [24]:
i2s[127]

'I-transport_type'